/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccumulableInfo { 
    ID?: number;
    Name?: string;
    Update?: any | null;
    Value?: any | null;
    Internal?: boolean;
    'Count Failed Values'?: boolean;
    Metadata?: any | null;
}

