/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccumulableInfo } from './accumulableInfo';


export interface AccumUpdate { 
    taskId?: number;
    accumUpdates?: Array<AccumulableInfo>;
    'Stage ID'?: number;
    'Stage Attempt ID'?: number;
}

