/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageLevel } from './storageLevel';
import { BlockManagerId } from './blockManagerId';


export interface BlockUpdatedInfo { 
    'Block Manager ID'?: BlockManagerId;
    'Block ID'?: string;
    'Storage Level'?: StorageLevel;
    'Memory Size'?: number;
    'Disk Size'?: number;
}

