/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccumulableInfo } from './accumulableInfo';
import { TaskEndReason } from './taskEndReason';
import { ExceptionFailureAllOfStackTrace } from './exceptionFailureAllOfStackTrace';


export interface ExceptionFailure extends TaskEndReason { 
    className?: string;
    description?: string;
    stackTrace?: Array<ExceptionFailureAllOfStackTrace>;
    fullStackTrace?: string;
    accumUpdates?: Array<AccumulableInfo>;
}

