/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceInformation } from './resourceInformation';


export interface ExecutorInfo { 
    Host?: string;
    'Total Cores'?: number;
    'Log Urls'?: { [key: string]: string; };
    Attributes?: { [key: string]: string; };
    Resources?: { [key: string]: ResourceInformation; };
    'Resource Profile Id'?: number;
    'Registration Time'?: number;
    'Request Time'?: number;
}

