/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExecutorMetrics { 
    otherMetrics?: { [key: string]: number; };
    otherProps?: { [key: string]: any; };
    JVMHeapMemory?: number;
    JVMOffHeapMemory?: number;
    OnHeapExecutionMemory?: number;
    OffHeapExecutionMemory?: number;
    OnHeapStorageMemory?: number;
    OffHeapStorageMemory?: number;
    OnHeapUnifiedMemory?: number;
    OffHeapUnifiedMemory?: number;
    DirectPoolMemory?: number;
    MappedPoolMemory?: number;
    ProcessTreeJVMVMemory?: number;
    ProcessTreeJVMRSSMemory?: number;
    ProcessTreePythonVMemory?: number;
    ProcessTreePythonRSSMemory?: number;
    ProcessTreeOtherVMemory?: number;
    ProcessTreeOtherRSSMemory?: number;
    MinorGCCount?: number;
    MinorGCTime?: number;
    MajorGCCount?: number;
    MajorGCTime?: number;
    TotalGCTime?: number;
}

