/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskEndReason } from './taskEndReason';
import { BlockManagerId } from './blockManagerId';


export interface FetchFailed extends TaskEndReason { 
    bmAddress?: BlockManagerId;
    shuffleId?: number;
    mapId?: number;
    mapIndex?: number;
    reduceId?: number;
    message?: string;
}

