/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkListenerApplicationStart } from './sparkListenerApplicationStart';
import { SparkListenerStageSubmitted } from './sparkListenerStageSubmitted';
import { SparkListenerTaskStart } from './sparkListenerTaskStart';
import { SparkListenerExecutorUnexcluded } from './sparkListenerExecutorUnexcluded';
import { SparkListenerSQLAdaptiveExecutionUpdate } from './sparkListenerSQLAdaptiveExecutionUpdate';
import { SparkListenerUnpersistRDD } from './sparkListenerUnpersistRDD';
import { TaskInfo } from './taskInfo';
import { SparkListenerBlockManagerRemoved } from './sparkListenerBlockManagerRemoved';
import { SparkListenerLogStart } from './sparkListenerLogStart';
import { SparkListenerNodeBlacklistedForStage } from './sparkListenerNodeBlacklistedForStage';
import { SparkListenerApplicationEnd } from './sparkListenerApplicationEnd';
import { SparkListenerNodeUnexcluded } from './sparkListenerNodeUnexcluded';
import { SparkListenerExecutorBlacklisted } from './sparkListenerExecutorBlacklisted';
import { SparkListenerUnschedulableTaskSetRemoved } from './sparkListenerUnschedulableTaskSetRemoved';
import { SparkListenerExecutorAdded } from './sparkListenerExecutorAdded';
import { SparkListenerSQLAdaptiveSQLMetricUpdates } from './sparkListenerSQLAdaptiveSQLMetricUpdates';
import { SparkListenerBlockManagerAdded } from './sparkListenerBlockManagerAdded';
import { SparkListenerExecutorUnblacklisted } from './sparkListenerExecutorUnblacklisted';
import { JobResult } from './jobResult';
import { SparkListenerJobEnd } from './sparkListenerJobEnd';
import { SparkListenerJobStart } from './sparkListenerJobStart';
import { AccumUpdate } from './accumUpdate';
import { SparkListenerTaskGettingResult } from './sparkListenerTaskGettingResult';
import { SparkListenerExecutorBlacklistedForStage } from './sparkListenerExecutorBlacklistedForStage';
import { SparkListenerBlockUpdated } from './sparkListenerBlockUpdated';
import { SparkListenerSpeculativeTaskSubmitted } from './sparkListenerSpeculativeTaskSubmitted';
import { SparkListenerExecutorExcludedForStage } from './sparkListenerExecutorExcludedForStage';
import { SparkListenerStageExecutorMetrics } from './sparkListenerStageExecutorMetrics';
import { SparkPlanInfo } from './sparkPlanInfo';
import { TaskMetrics } from './taskMetrics';
import { SparkListenerNodeBlacklisted } from './sparkListenerNodeBlacklisted';
import { ExecutorMetrics } from './executorMetrics';
import { SparkListenerExecutorExcluded } from './sparkListenerExecutorExcluded';
import { SparkListenerTaskEnd } from './sparkListenerTaskEnd';
import { StageInfo } from './stageInfo';
import { SparkListenerUnschedulableTaskSetAdded } from './sparkListenerUnschedulableTaskSetAdded';
import { SparkListenerNodeUnblacklisted } from './sparkListenerNodeUnblacklisted';
import { SparkListenerSQLExecutionStart } from './sparkListenerSQLExecutionStart';
import { ExecutorInfo } from './executorInfo';
import { SQLPlanMetric } from './sQLPlanMetric';
import { SparkListenerEnvironmentUpdate } from './sparkListenerEnvironmentUpdate';
import { SparkListenerTaskEndAllOfTaskEndReason } from './sparkListenerTaskEndAllOfTaskEndReason';
import { ExecutorResourceRequest } from './executorResourceRequest';
import { BlockUpdatedInfo } from './blockUpdatedInfo';
import { SparkListenerExecutorMetricsUpdate } from './sparkListenerExecutorMetricsUpdate';
import { BlockManagerId } from './blockManagerId';
import { SparkListenerDriverAccumUpdates } from './sparkListenerDriverAccumUpdates';
import { SparkListenerSQLExecutionEnd } from './sparkListenerSQLExecutionEnd';
import { SparkListenerNodeExcludedForStage } from './sparkListenerNodeExcludedForStage';
import { SparkListenerExecutorRemoved } from './sparkListenerExecutorRemoved';
import { SparkListenerNodeExcluded } from './sparkListenerNodeExcluded';
import { SparkListenerResourceProfileAdded } from './sparkListenerResourceProfileAdded';
import { SparkListenerStageCompleted } from './sparkListenerStageCompleted';


/**
 * @type FindByNum200Response
 * @export
 */
export type FindByNum200Response = SparkListenerApplicationEnd | SparkListenerApplicationStart | SparkListenerBlockManagerAdded | SparkListenerBlockManagerRemoved | SparkListenerBlockUpdated | SparkListenerDriverAccumUpdates | SparkListenerEnvironmentUpdate | SparkListenerExecutorAdded | SparkListenerExecutorBlacklisted | SparkListenerExecutorBlacklistedForStage | SparkListenerExecutorExcluded | SparkListenerExecutorExcludedForStage | SparkListenerExecutorMetricsUpdate | SparkListenerExecutorRemoved | SparkListenerExecutorUnblacklisted | SparkListenerExecutorUnexcluded | SparkListenerJobEnd | SparkListenerJobStart | SparkListenerLogStart | SparkListenerNodeBlacklisted | SparkListenerNodeBlacklistedForStage | SparkListenerNodeExcluded | SparkListenerNodeExcludedForStage | SparkListenerNodeUnblacklisted | SparkListenerNodeUnexcluded | SparkListenerResourceProfileAdded | SparkListenerSQLAdaptiveExecutionUpdate | SparkListenerSQLAdaptiveSQLMetricUpdates | SparkListenerSQLExecutionEnd | SparkListenerSQLExecutionStart | SparkListenerSpeculativeTaskSubmitted | SparkListenerStageCompleted | SparkListenerStageExecutorMetrics | SparkListenerStageSubmitted | SparkListenerTaskEnd | SparkListenerTaskGettingResult | SparkListenerTaskStart | SparkListenerUnpersistRDD | SparkListenerUnschedulableTaskSetAdded | SparkListenerUnschedulableTaskSetRemoved;

