/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MetricValueHolderSummary { 
    name?: string;
    accId?: number;
    metricType?: string;
    valuesUpdateCount?: number;
    lastValue?: number;
    min?: number;
    max?: number;
    fromJobId?: number;
    fromStageId?: number;
}

