/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NodeEqualSemanticDuplicatesEntryDTO } from './nodeEqualSemanticDuplicatesEntryDTO';


export interface NodeDuplicatesWithinSqlExecAnalysisDTO { 
    sameDuplicatesEntries?: Array<NodeEqualSemanticDuplicatesEntryDTO>;
    semanticDuplicatesEntries?: Array<NodeEqualSemanticDuplicatesEntryDTO>;
}

