/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageLevel } from './storageLevel';


export interface RDDInfo { 
    'RDD ID'?: number;
    Name?: string;
    Scope?: string;
    Callsite?: string;
    'Parent IDs'?: Array<number>;
    'Storage Level'?: StorageLevel;
    Barrier?: boolean;
    DeterministicLevel?: string;
    'Number of Partitions'?: number;
    'Number of Cached Partitions'?: number;
    'Memory Size'?: number;
    'Disk Size'?: number;
}

