/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShufflePushReadMetrics } from './shufflePushReadMetrics';


export interface ShuffleReadMetrics { 
    'Remote Blocks Fetched'?: number;
    'Local Blocks Fetched'?: number;
    'Fetch Wait Time'?: number;
    'Remote Bytes Read'?: number;
    'Remote Bytes Read To Disk'?: number;
    'Local Bytes Read'?: number;
    'Total Records Read'?: number;
    'Remote Requests Duration'?: number;
    'Push Based Shuffle'?: ShufflePushReadMetrics;
}

