/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShufflePushReadMetrics { 
    'Corrupt Merged Block Chunks'?: number;
    'Merged Fetch Fallback Count'?: number;
    'Merged Remote Blocks Fetched'?: number;
    'Merged Local Blocks Fetched'?: number;
    'Merged Remote Chunks Fetched'?: number;
    'Merged Local Chunks Fetched'?: number;
    'Merged Remote Bytes Read'?: number;
    'Merged Local Bytes Read'?: number;
    'Merged Remote Requests Duration'?: number;
}

