/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SparkApplicationConfigDTO { 
    sparkVersion?: string;
    javaVersion?: string;
    javaHome?: string;
    scalaVersion?: string;
    jvmInformation?: { [key: string]: string; };
    sparkProperties?: { [key: string]: string; };
    hadoopProperties?: { [key: string]: string; };
    systemProperties?: { [key: string]: string; };
    classpathEntries?: { [key: string]: string; };
    metricsProperties?: { [key: string]: string; };
    otherEnvironmentDetails?: { [key: string]: { [key: string]: string; }; };
    executorCore?: number;
    defaultCpusPerTask?: number;
    coresGranted?: number;
    maxCores?: number;
    coresPerExecutor?: number;
    memoryPerExecutorMB?: number;
}

