/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkEvent } from './sparkEvent';


export interface SparkListenerEnvironmentUpdate extends SparkEvent { 
    otherEnvironmentDetails?: { [key: string]: { [key: string]: string; }; };
    'JVM Information'?: { [key: string]: string; };
    'Spark Properties'?: { [key: string]: string; };
    'Hadoop Properties'?: { [key: string]: string; };
    'System Properties'?: { [key: string]: string; };
    'Classpath Entries'?: { [key: string]: string; };
    'Metrics Properties'?: { [key: string]: string; };
}

