/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkPlanInfo } from './sparkPlanInfo';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerSQLAdaptiveExecutionUpdate extends SparkEvent { 
    executionId?: number;
    physicalPlanDescription?: string;
    sparkPlanInfo?: SparkPlanInfo;
}

