/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkNodeExcludedEventSummaryDTO extends SparkEventSummaryDTO { 
    hostId?: string;
    executorFailures?: number;
    t?: number;
}

