/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkEvent } from './sparkEvent';


export interface SparkListenerDriverAccumUpdates extends SparkEvent { 
    executionId?: number;
    accumUpdates?: Array<Array<number>>;
}

