/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobResult } from './jobResult';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerJobEnd extends SparkEvent { 
    'Job ID'?: number;
    'Completion Time'?: number;
    'Job Result'?: JobResult;
}

