/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkPlanInfo } from './sparkPlanInfo';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerSQLExecutionStart extends SparkEvent { 
    rootExecutionId?: number;
    executionId?: number;
    description?: string;
    details?: string;
    physicalPlanDescription?: string;
    sparkPlanInfo?: SparkPlanInfo;
    modifiedConfigs?: { [key: string]: string; };
    time?: number;
    jobTags?: Set<string>;
    jobGroupId?: string;
}

