/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkListenerLogStart } from './sparkListenerLogStart';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkLogStartEventSummaryDTO extends SparkEventSummaryDTO { 
    event?: SparkListenerLogStart;
}

