/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkPlanInfoSummaryDTO } from './sparkPlanInfoSummaryDTO';
import { CallSiteTemplatedStringDTO } from './callSiteTemplatedStringDTO';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';
import { SparkListenerSQLAdaptiveExecutionUpdate } from './sparkListenerSQLAdaptiveExecutionUpdate';


export interface SparkSQLExecutionEventSummaryDTO extends SparkEventSummaryDTO { 
    execId?: number;
    startTime?: number;
    callSiteTemplated?: CallSiteTemplatedStringDTO;
    modifiedConfigs?: { [key: string]: string; };
    lastSQLAdaptiveExecutionUpdateEvent?: SparkListenerSQLAdaptiveExecutionUpdate;
    physicalPlanDescriptionTemplateId?: number;
    plan?: SparkPlanInfoSummaryDTO;
    endEventNum?: number;
    duration?: number;
    endErrorMessage?: string;
}

