/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutorInfo } from './executorInfo';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkExecutorAddedEventSummaryDTO extends SparkEventSummaryDTO { 
    t?: number;
    execId?: string;
    executorInfo?: ExecutorInfo;
}

