/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkEvent } from './sparkEvent';


export interface SparkListenerExecutorExcludedForStage extends SparkEvent { 
    taskFailures?: number;
    Timestamp?: number;
    'Executor ID'?: string;
    'Stage ID'?: number;
    'Stage Attempt ID'?: number;
}

