/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SQLPlanMetric } from './sQLPlanMetric';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerSQLAdaptiveSQLMetricUpdates extends SparkEvent { 
    executionId?: number;
    sqlPlanMetrics?: Array<SQLPlanMetric>;
}

