/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlockUpdatedInfo } from './blockUpdatedInfo';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerBlockUpdated extends SparkEvent { 
    blockUpdatedInfo?: BlockUpdatedInfo;
}

