/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutorMetrics } from './executorMetrics';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerStageExecutorMetrics extends SparkEvent { 
    execId?: string;
    executorMetrics?: ExecutorMetrics;
    'Stage ID'?: number;
    'Stage Attempt ID'?: number;
}

