/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkListenerBlockManagerAdded } from './sparkListenerBlockManagerAdded';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkBlockManagerAddedEventSummaryDTO extends SparkEventSummaryDTO { 
    event?: SparkListenerBlockManagerAdded;
}

