/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkListenerApplicationEnd } from './sparkListenerApplicationEnd';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkApplicationEndEventSummaryDTO extends SparkEventSummaryDTO { 
    event?: SparkListenerApplicationEnd;
}

