/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccumulableInfo } from './accumulableInfo';
import { ExecutorLostFailure } from './executorLostFailure';
import { UnknownReason } from './unknownReason';
import { ExceptionFailure } from './exceptionFailure';
import { TaskCommitDenied } from './taskCommitDenied';
import { FetchFailed } from './fetchFailed';
import { Resubmitted } from './resubmitted';
import { ExceptionFailureAllOfStackTrace } from './exceptionFailureAllOfStackTrace';
import { TaskKilled } from './taskKilled';
import { Success } from './success';
import { TaskResultLost } from './taskResultLost';
import { BlockManagerId } from './blockManagerId';


/**
 * @type SparkListenerTaskEndAllOfTaskEndReason
 * @export
 */
export type SparkListenerTaskEndAllOfTaskEndReason = ExceptionFailure | ExecutorLostFailure | FetchFailed | Resubmitted | Success | TaskCommitDenied | TaskKilled | TaskResultLost | UnknownReason;

