/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlockManagerId } from './blockManagerId';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerBlockManagerRemoved extends SparkEvent { 
    Timestamp?: number;
    'Block Manager ID'?: BlockManagerId;
    'Maximum Memory'?: number;
}

