/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskInfo } from './taskInfo';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerTaskStart extends SparkEvent { 
    'Stage ID'?: number;
    'Stage Attempt ID'?: number;
    'Task Info'?: TaskInfo;
}

