/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkListenerEnvironmentUpdate } from './sparkListenerEnvironmentUpdate';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkEnvironmentUpdateEventSummaryDTO extends SparkEventSummaryDTO { 
    event?: SparkListenerEnvironmentUpdate;
}

