/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StackTraceDTO } from './stackTraceDTO';


export interface SparkException { 
    Message?: string;
    'Stack Trace'?: Array<StackTraceDTO>;
}

