/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkExecutorUnexcludedEventSummaryDTO extends SparkEventSummaryDTO { 
    t?: number;
    execId?: string;
}

