/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewCallSiteLongTemplateEventSummaryDTO } from './newCallSiteLongTemplateEventSummaryDTO';
import { SparkEnvironmentUpdateEventSummaryDTO } from './sparkEnvironmentUpdateEventSummaryDTO';
import { SparkException } from './sparkException';
import { SparkApplicationEndEventSummaryDTO } from './sparkApplicationEndEventSummaryDTO';
import { SparkBlockManagerAddedEventSummaryDTO } from './sparkBlockManagerAddedEventSummaryDTO';
import { SparkNodeExcludedForStageEventSummaryDTO } from './sparkNodeExcludedForStageEventSummaryDTO';
import { SparkListenerSQLAdaptiveExecutionUpdate } from './sparkListenerSQLAdaptiveExecutionUpdate';
import { NewPlanDescriptionTemplateEventSummaryDTO } from './newPlanDescriptionTemplateEventSummaryDTO';
import { SparkLogStartEventSummaryDTO } from './sparkLogStartEventSummaryDTO';
import { SparkPlanInfoSummaryDTO } from './sparkPlanInfoSummaryDTO';
import { NewCallSiteShortTemplateEventSummaryDTO } from './newCallSiteShortTemplateEventSummaryDTO';
import { ExecutorInfo } from './executorInfo';
import { SparkBlockManagerRemovedEventSummaryDTO } from './sparkBlockManagerRemovedEventSummaryDTO';
import { SparkExecutorRemovedEventSummaryDTO } from './sparkExecutorRemovedEventSummaryDTO';
import { SparkExecutorExcludedForStageEventSummaryDTO } from './sparkExecutorExcludedForStageEventSummaryDTO';
import { SparkExecutorUnexcludedEventSummaryDTO } from './sparkExecutorUnexcludedEventSummaryDTO';
import { SparkNodeUnexcludedEventSummaryDTO } from './sparkNodeUnexcludedEventSummaryDTO';
import { CallSiteTemplatedStringDTO } from './callSiteTemplatedStringDTO';
import { SparkNodeExcludedEventSummaryDTO } from './sparkNodeExcludedEventSummaryDTO';
import { SparkResourceProfileAddedEventSummaryDTO } from './sparkResourceProfileAddedEventSummaryDTO';
import { TemplateStringEntryDTO } from './templateStringEntryDTO';
import { SparkExecutorExcludedEventSummaryDTO } from './sparkExecutorExcludedEventSummaryDTO';
import { SparkApplicationStartEventSummaryDTO } from './sparkApplicationStartEventSummaryDTO';
import { SparkTopLevelJobExecEventSummaryDTO } from './sparkTopLevelJobExecEventSummaryDTO';
import { SparkListenerResourceProfileAdded } from './sparkListenerResourceProfileAdded';
import { SparkExecutorAddedEventSummaryDTO } from './sparkExecutorAddedEventSummaryDTO';
import { SparkSQLExecutionEventSummaryDTO } from './sparkSQLExecutionEventSummaryDTO';


/**
 * @type SparkAppEventSummaries200ResponseInner
 * @export
 */
export type SparkAppEventSummaries200ResponseInner = NewCallSiteLongTemplateEventSummaryDTO | NewCallSiteShortTemplateEventSummaryDTO | NewPlanDescriptionTemplateEventSummaryDTO | SparkApplicationEndEventSummaryDTO | SparkApplicationStartEventSummaryDTO | SparkBlockManagerAddedEventSummaryDTO | SparkBlockManagerRemovedEventSummaryDTO | SparkEnvironmentUpdateEventSummaryDTO | SparkExecutorAddedEventSummaryDTO | SparkExecutorExcludedEventSummaryDTO | SparkExecutorExcludedForStageEventSummaryDTO | SparkExecutorRemovedEventSummaryDTO | SparkExecutorUnexcludedEventSummaryDTO | SparkLogStartEventSummaryDTO | SparkNodeExcludedEventSummaryDTO | SparkNodeExcludedForStageEventSummaryDTO | SparkNodeUnexcludedEventSummaryDTO | SparkResourceProfileAddedEventSummaryDTO | SparkSQLExecutionEventSummaryDTO | SparkTopLevelJobExecEventSummaryDTO;

