/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetricValueHolderSummary } from './metricValueHolderSummary';


export interface SparkPlanInfoSummaryDTO { 
    nodeName?: string;
    simpleString?: string;
    children?: Array<any>;
    metadata?: { [key: string]: any; };
    metrics?: Array<MetricValueHolderSummary>;
}

