/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StageInfo } from './stageInfo';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerStageCompleted extends SparkEvent { 
    'Stage Info'?: StageInfo;
}

