/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccumUpdate } from './accumUpdate';
import { ExecutorMetrics } from './executorMetrics';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerExecutorMetricsUpdate extends SparkEvent { 
    execId?: string;
    accumUpdates?: Array<AccumUpdate>;
    executorUpdates?: { [key: string]: ExecutorMetrics; };
}

