/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskInfo } from './taskInfo';
import { TaskMetrics } from './taskMetrics';
import { SparkListenerTaskEndAllOfTaskEndReason } from './sparkListenerTaskEndAllOfTaskEndReason';
import { ExecutorMetrics } from './executorMetrics';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerTaskEnd extends SparkEvent { 
    'Stage ID'?: number;
    'Stage Attempt ID'?: number;
    'Task Type'?: string;
    'Task End Reason'?: SparkListenerTaskEndAllOfTaskEndReason;
    'Task Info'?: TaskInfo;
    'Task Executor Metrics'?: ExecutorMetrics;
    'Task Metrics'?: TaskMetrics;
    Metadata?: { [key: string]: any; };
}

