/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutorInfo } from './executorInfo';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerExecutorAdded extends SparkEvent { 
    Timestamp?: number;
    'Executor ID'?: string;
    'Executor Info'?: ExecutorInfo;
}

