/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkListenerResourceProfileAdded } from './sparkListenerResourceProfileAdded';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkResourceProfileAddedEventSummaryDTO extends SparkEventSummaryDTO { 
    event?: SparkListenerResourceProfileAdded;
}

