/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkListenerApplicationStart } from './sparkListenerApplicationStart';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkApplicationStartEventSummaryDTO extends SparkEventSummaryDTO { 
    event?: SparkListenerApplicationStart;
}

