/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutorResourceRequest } from './executorResourceRequest';
import { SparkEvent } from './sparkEvent';


export interface SparkListenerResourceProfileAdded extends SparkEvent { 
    resourceProfile?: any | null;
    'Resource Profile Id'?: number;
    'Executor Resource Requests'?: { [key: string]: ExecutorResourceRequest; };
    'Task Resource Requests'?: { [key: string]: ExecutorResourceRequest; };
}

