/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkException } from './sparkException';
import { CallSiteTemplatedStringDTO } from './callSiteTemplatedStringDTO';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkTopLevelJobExecEventSummaryDTO extends SparkEventSummaryDTO { 
    jobId?: number;
    submitTime?: number;
    propOverrides?: { [key: string]: string; };
    callSiteTemplated?: CallSiteTemplatedStringDTO;
    duration?: number;
    result?: string;
    resultEx?: SparkException;
}

