/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkEvent } from './sparkEvent';


export interface SparkListenerApplicationStart extends SparkEvent { 
    'App Name'?: string;
    'App ID'?: string;
    Timestamp?: number;
    User?: string;
    'App Attempt ID'?: string;
    'Driver Logs'?: { [key: string]: string; };
    'Driver Attributes'?: { [key: string]: string; };
}

