/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SparkListenerBlockManagerRemoved } from './sparkListenerBlockManagerRemoved';
import { SparkEventSummaryDTO } from './sparkEventSummaryDTO';


export interface SparkBlockManagerRemovedEventSummaryDTO extends SparkEventSummaryDTO { 
    event?: SparkListenerBlockManagerRemoved;
}

