/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StackTraceDTO { 
    'Declaring Class'?: string;
    'Method Name'?: string;
    'File Name'?: string;
    'Line Number'?: number;
}

