/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccumulableInfo } from './accumulableInfo';
import { TaskMetrics } from './taskMetrics';
import { RDDInfo } from './rDDInfo';


export interface StageInfo { 
    'Stage ID'?: number;
    'Stage Attempt ID'?: number;
    'Stage Name'?: string;
    'Number of Tasks'?: number;
    'RDD Info'?: Array<RDDInfo>;
    'Parent IDs'?: Array<number>;
    Details?: string;
    'Task Metrics'?: TaskMetrics;
    'Resource Profile Id'?: number;
    'Submission Time'?: number;
    'Completion Time'?: number;
    'Failure Reason'?: string;
    Accumulables?: Array<AccumulableInfo>;
    'Shuffle Push Enabled'?: boolean;
    'Shuffle Push Mergers Count'?: number;
}

