/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StorageLevel { 
    valid?: boolean;
    'Use Disk'?: boolean;
    'Use Memory'?: boolean;
    'Use Off Heap'?: boolean;
    Deserialized?: boolean;
    Replication?: number;
}

