/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccumulableInfo } from './accumulableInfo';


export interface TaskInfo { 
    'Task ID'?: number;
    Index?: number;
    Attempt?: number;
    'Partition ID'?: number;
    'Launch Time'?: number;
    'Executor ID'?: string;
    Host?: string;
    Locality?: string;
    Speculative?: boolean;
    'Getting Result Time'?: number;
    'Finish Time'?: number;
    Failed?: boolean;
    Killed?: boolean;
    Accumulables?: Array<AccumulableInfo>;
}

