/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutputMetrics } from './outputMetrics';
import { BlockIdStatus } from './blockIdStatus';
import { ShuffleReadMetrics } from './shuffleReadMetrics';
import { InputMetrics } from './inputMetrics';
import { ShuffleWriteMetrics } from './shuffleWriteMetrics';


export interface TaskMetrics { 
    'Executor Deserialize Time'?: number;
    'Executor Deserialize CPU Time'?: number;
    'Executor Run Time'?: number;
    'Executor CPU Time'?: number;
    'Result Size'?: number;
    'JVM GC Time'?: number;
    'Result Serialization Time'?: number;
    'Memory Bytes Spilled'?: number;
    'Disk Bytes Spilled'?: number;
    'Peak Execution Memory'?: number;
    'Input Metrics'?: InputMetrics;
    'Output Metrics'?: OutputMetrics;
    'Shuffle Read Metrics'?: ShuffleReadMetrics;
    'Shuffle Write Metrics'?: ShuffleWriteMetrics;
    'Updated Blocks'?: Array<BlockIdStatus>;
}

