/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccumulableInfo } from './accumulableInfo';
import { TaskEndReason } from './taskEndReason';


export interface TaskKilled extends TaskEndReason { 
    reason?: string;
    accumUpdates?: Array<AccumulableInfo>;
    metricPeaks?: Array<number>;
}

