/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TemplateStringEntryDTO } from './templateStringEntryDTO';


export interface TemplateDictionariesEntriesDTO { 
    callSiteShortEntries?: Array<TemplateStringEntryDTO>;
    callSiteLongEntries?: Array<TemplateStringEntryDTO>;
    planDescriptionEntries?: Array<TemplateStringEntryDTO>;
}

