/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { NodeDuplicatesWithinSqlExecAnalysisDTO } from '../model/nodeDuplicatesWithinSqlExecAnalysisDTO';
// @ts-ignore
import { SparkAppEventSummaries200ResponseInner } from '../model/sparkAppEventSummaries200ResponseInner';
// @ts-ignore
import { SparkAppSummaryDTO } from '../model/sparkAppSummaryDTO';
// @ts-ignore
import { SparkClusterDTO } from '../model/sparkClusterDTO';
// @ts-ignore
import { SqlExecutionEventsDTO } from '../model/sqlExecutionEventsDTO';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class SparkAppsRestControllerService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param clusterName 
     * @param sparkAppName 
     * @param sqlId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public analyseNodeDuplicatesWithinSqlExec(clusterName: string, sparkAppName: string, sqlId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<NodeDuplicatesWithinSqlExecAnalysisDTO>;
    public analyseNodeDuplicatesWithinSqlExec(clusterName: string, sparkAppName: string, sqlId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<NodeDuplicatesWithinSqlExecAnalysisDTO>>;
    public analyseNodeDuplicatesWithinSqlExec(clusterName: string, sparkAppName: string, sqlId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<NodeDuplicatesWithinSqlExecAnalysisDTO>>;
    public analyseNodeDuplicatesWithinSqlExec(clusterName: string, sparkAppName: string, sqlId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (clusterName === null || clusterName === undefined) {
            throw new Error('Required parameter clusterName was null or undefined when calling analyseNodeDuplicatesWithinSqlExec.');
        }
        if (sparkAppName === null || sparkAppName === undefined) {
            throw new Error('Required parameter sparkAppName was null or undefined when calling analyseNodeDuplicatesWithinSqlExec.');
        }
        if (sqlId === null || sqlId === undefined) {
            throw new Error('Required parameter sqlId was null or undefined when calling analyseNodeDuplicatesWithinSqlExec.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/spark-apps/cluster/${this.configuration.encodeParam({name: "clusterName", value: clusterName, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/spark-app/${this.configuration.encodeParam({name: "sparkAppName", value: sparkAppName, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/sql/${this.configuration.encodeParam({name: "sqlId", value: sqlId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int64"})}/node-duplicates-analysis`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<NodeDuplicatesWithinSqlExecAnalysisDTO>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param clusterName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCluster(clusterName: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<SparkClusterDTO>;
    public getCluster(clusterName: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SparkClusterDTO>>;
    public getCluster(clusterName: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SparkClusterDTO>>;
    public getCluster(clusterName: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (clusterName === null || clusterName === undefined) {
            throw new Error('Required parameter clusterName was null or undefined when calling getCluster.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/spark-apps/cluster/${this.configuration.encodeParam({name: "clusterName", value: clusterName, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SparkClusterDTO>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param clusterName 
     * @param sparkAppName 
     * @param sqlId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSqlExecutionEvents(clusterName: string, sparkAppName: string, sqlId: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<SqlExecutionEventsDTO>;
    public getSqlExecutionEvents(clusterName: string, sparkAppName: string, sqlId: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SqlExecutionEventsDTO>>;
    public getSqlExecutionEvents(clusterName: string, sparkAppName: string, sqlId: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SqlExecutionEventsDTO>>;
    public getSqlExecutionEvents(clusterName: string, sparkAppName: string, sqlId: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (clusterName === null || clusterName === undefined) {
            throw new Error('Required parameter clusterName was null or undefined when calling getSqlExecutionEvents.');
        }
        if (sparkAppName === null || sparkAppName === undefined) {
            throw new Error('Required parameter sparkAppName was null or undefined when calling getSqlExecutionEvents.');
        }
        if (sqlId === null || sqlId === undefined) {
            throw new Error('Required parameter sqlId was null or undefined when calling getSqlExecutionEvents.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/spark-apps/cluster/${this.configuration.encodeParam({name: "clusterName", value: clusterName, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/spark-app/${this.configuration.encodeParam({name: "sparkAppName", value: sparkAppName, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/sql/${this.configuration.encodeParam({name: "sqlId", value: sqlId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int64"})}/events`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SqlExecutionEventsDTO>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param clusterName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listClusterSparkAppSummaries(clusterName: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<SparkAppSummaryDTO>>;
    public listClusterSparkAppSummaries(clusterName: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<SparkAppSummaryDTO>>>;
    public listClusterSparkAppSummaries(clusterName: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<SparkAppSummaryDTO>>>;
    public listClusterSparkAppSummaries(clusterName: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (clusterName === null || clusterName === undefined) {
            throw new Error('Required parameter clusterName was null or undefined when calling listClusterSparkAppSummaries.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/spark-apps/cluster/${this.configuration.encodeParam({name: "clusterName", value: clusterName, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/spark-apps`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<SparkAppSummaryDTO>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listClusters(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<SparkClusterDTO>>;
    public listClusters(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<SparkClusterDTO>>>;
    public listClusters(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<SparkClusterDTO>>>;
    public listClusters(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/spark-apps/clusters`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<SparkClusterDTO>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param clusterName 
     * @param sparkAppName 
     * @param from 
     * @param limit 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sparkAppEventSummaries(clusterName: string, sparkAppName: string, from?: number, limit?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<SparkAppEventSummaries200ResponseInner>>;
    public sparkAppEventSummaries(clusterName: string, sparkAppName: string, from?: number, limit?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<SparkAppEventSummaries200ResponseInner>>>;
    public sparkAppEventSummaries(clusterName: string, sparkAppName: string, from?: number, limit?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<SparkAppEventSummaries200ResponseInner>>>;
    public sparkAppEventSummaries(clusterName: string, sparkAppName: string, from?: number, limit?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (clusterName === null || clusterName === undefined) {
            throw new Error('Required parameter clusterName was null or undefined when calling sparkAppEventSummaries.');
        }
        if (sparkAppName === null || sparkAppName === undefined) {
            throw new Error('Required parameter sparkAppName was null or undefined when calling sparkAppEventSummaries.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>from, 'from');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>limit, 'limit');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/spark-apps/cluster/${this.configuration.encodeParam({name: "clusterName", value: clusterName, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/spark-app/${this.configuration.encodeParam({name: "sparkAppName", value: sparkAppName, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/event-summaries`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<SparkAppEventSummaries200ResponseInner>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
